# Generated by Django 2.0.4 on 2018-05-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(help_text='Enter the diagnosis', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_medical_history',
            field=models.TextField(help_text='Enter previous disorders', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(help_text='Enter a brief description of the symptoms', max_length=1000, null=True),
        ),
    ]
