# Generated by Django 2.0.4 on 2018-05-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180502_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.TextField(blank=True, help_text='Enter the treatment', max_length=1000, null=True),
        ),
    ]
