# Generated by Django 2.0.4 on 2018-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_patient_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('e', 'Expected'), ('a', 'Admitted'), ('c', 'Cancelled')], default='e', help_text='Patient appointment status', max_length=1),
        ),
    ]
