# Generated by Django 2.0.4 on 2018-05-03 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular patient for records', primary_key=True, serialize=False),
        ),
    ]
