# Generated by Django 2.0.4 on 2018-05-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_patient_doctor_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_assign_patient', 'Set patient as assigned'),)},
        ),
    ]
