# Generated by Django 2.0.4 on 2018-05-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180503_0434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_assign_patient', 'Set patient as assigned'), ('can_treat_patient', 'User can treat patients'))},
        ),
    ]
